name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - dash
  - dash-html-components
  - plotly
  - python
  - numpy
  - gunicorn
  - flask
# conda-lock -f environment.yml -p linux-64
