services:

  ocgy25:
    build:
      context: ocgy-dataviewer
      dockerfile: Dockerfile
    image: phaustin/ocgy25:2025
    labels:
      - traefik.enable=true
      - traefik.http.routers.ocgy25.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/ocgy`)
      - traefik.http.routers.ocgy25.tls=true
      - traefik.http.routers.ocgy25.tls.certresolver=lets-encrypt
      - traefik.http.routers.ocgy25.service=ocgy25
      - traefik.http.services.ocgy25.loadbalancer.server.port=8050
      - traefik.http.routers.ocgy25.middlewares=ocgy25-stripprefix
      - traefik.http.middlewares.ocgy25-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.ocgy25-stripprefix.stripprefix.prefixes=/ocgy
    container_name: ocgy25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=10 --threads=2 -b 0.0.0.0:8050 app:server

networks:
  proxy_aug07:
    external: true
