version: '3.7'

services:

  mohrs:
    build:
      context: ocgy-dataviewer
      dockerfile: Dockerfile
    image: phaustin/ocgy:nov24
    labels:
      - traefik.enable=true
      - traefik.http.routers.mohrs.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/ocgy24`)
      - traefik.http.routers.mohrs.tls=true
      - traefik.http.routers.mohrs.tls.certresolver=lets-encrypt
      - traefik.http.routers.mohrs.service=mohrs
      - traefik.http.services.mohrs.loadbalancer.server.port=8050
      - traefik.http.routers.mohrs.middlewares=mohrs-stripprefix
      - traefik.http.middlewares.mohrs-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.mohrs-stripprefix.stripprefix.prefixes=/mohrs
    container_name: ocgy24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=10 --threads=2 -b 0.0.0.0:8050 app:server

networks:
  proxy_aug07:
    external: true
