version: '3.7'

services:

  ocgy24:
    build:
      context: ocgy-dataviewer
      dockerfile: Dockerfile
    image: phaustin/ocgy24:nov24
    labels:
      - traefik.enable=true
      - traefik.http.routers.ocgy24.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/ocgy24`)
      - traefik.http.routers.ocgy24.tls=true
      - traefik.http.routers.ocgy24.tls.certresolver=lets-encrypt
      - traefik.http.routers.ocgy24.service=ocgy24
      - traefik.http.services.ocgy24.loadbalancer.server.port=8050
      - traefik.http.routers.ocgy24.middlewares=ocgy24-stripprefix
      - traefik.http.middlewares.ocgy24-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.ocgy24-stripprefix.stripprefix.prefixes=/ocgy24
    container_name: ocgy24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=10 --threads=2 -b 0.0.0.0:8050 app:server

networks:
  proxy_aug07:
    external: true
