services:

  globaltemps25:
    build:
      context: globaltemps
      dockerfile: Dockerfile
    image: phaustin/globaltemps25:2025
    labels:
      - traefik.enable=true
      - traefik.http.routers.globaltemps25.rule=Host(`dashboard.eoas.ubc.ca`) && PathPrefix(`/globaltemps`)
      - traefik.http.routers.globaltemps25.tls=true
      - traefik.http.routers.globaltemps25.tls.certresolver=lets-encrypt
      - traefik.http.routers.globaltemps25.service=globaltemps25
      - traefik.http.services.globaltemps25.loadbalancer.server.port=8050
      - traefik.http.routers.globaltemps25.middlewares=globaltemps25-stripprefix
      - traefik.http.middlewares.globaltemps25-stripprefix.stripprefix.forceSlash=true
      - traefik.http.middlewares.globaltemps25-stripprefix.stripprefix.prefixes=/globaltemps
    container_name: globaltemps25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=10 --threads=2 -b 0.0.0.0:8050 app:server

networks:
  proxy_aug07:
    external: true
