name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - dash
  - python
  - gunicorn
  - flask
  - pip
  - pandas
  - conda-lock
  - plotly
  - numpy
  - gsw
  
# conda-lock -f environment.yml -p linux-64
