name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - pip
  - python
  - click
  - dash
  - dash-html-components
  - flask
  - gunicorn
  - plotly
  - pandas
# conda-lock -f environment.yml -p linux-64
