name: notebook
channels:
  - eoas_ubc
  - conda-forge
dependencies:
  - dash
  - dash-html-components
  - pip
  - plotly
  - python
  - gunicorn
  - flask
  - pandas
  - scikit-image
  - conda-lock
# conda-lock -f environment.yml -p linux-64 -p osx-arm64
